name: Release workflow for tagged versions
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v0.2.19, v0.2.14a

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v1

      - name: Build and release binaries
        uses: wangyoucao577/go-release-action@v1.19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/pghba"
          extra_files: LICENSE README.md
          pre_command: ./set_version.sh
          sha256sum: TRUE

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: set_version
        run: ./set_version.sh
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: "Build"
        run: |
          docker build -t pghba .
      - name: "tag and push to ghcr.io"
        run: |
          for TAG in latest ${{ github.ref_name }}; do
            docker tag pghba ghcr.io/mannemsolutions/pghba:${TAG}
            docker push ghcr.io/mannemsolutions/pghba:${TAG}
          done
